import {RealSenseSource} from './depth-source.js';
import {drawDepth,TrajectoryRenderer} from './render.js';
const $=id=>document.getElementById(id);const source=new RealSenseSource();const trajView=new TrajectoryRenderer($('trajectoryCanvas'));const worker=new Worker(new URL('./slam-worker.js',import.meta.url),{type:'classic'});
let running=false,busy=false,dropped=0,lastSent=0,lastRgbDesc=null,lastRgbDescAt=0,frameCb=null,path=[],keyframePath=[],originMatrix=null,trajectoryRows=[];
$('refreshBtn').onclick=refresh;$('startBtn').onclick=()=>running?stop():start();$('resetOriginBtn').onclick=()=>{originMatrix=currentMatrix?currentMatrix.slice():null;};$('resetMapBtn').onclick=()=>worker.postMessage({type:'reset'});$('benchmarkBtn').onclick=()=>worker.postMessage({type:'benchmark'});$('exportCsvBtn').onclick=exportCsv;window.addEventListener('beforeunload',()=>source.stop());
let currentRawPose=null,currentMatrix=null;
worker.onmessage=e=>{const m=e.data;if(m.type==='result'){busy=false;renderResult(m);}else if(m.type==='benchmark'){const el=$('benchmarkState');el.textContent=`Synthetic 320×240: median ${m.median.toFixed(1)} ms · p95 ${m.p95.toFixed(1)} ms · recommended ${m.recommendedHz} Hz`;el.style.color=m.median<40?'#3fb950':'#d29922';}else if(m.type==='reset'){busy=false;path=[];keyframePath=[];originMatrix=null;trajectoryRows=[];trajView.render([],[]);}};
async function refresh(){setCam('Requesting camera permission…');$('refreshBtn').disabled=true;try{const ds=await source.enumerate();const depth=ds.filter(d=>/depth/i.test(d.label));const rgb=ds.filter(d=>!/depth/i.test(d.label)&&(/rgb|color|435/i.test(d.label)));fill($('depthDevice'),depth,'No RealSense Depth input found');fill($('rgbDevice'),rgb,'None',true);if(depth.length)setCam(`${depth.length} Depth input${depth.length===1?'':'s'} found. RGB is optional.`,'ok');else setCam('No browser-visible RealSense Depth input found.','bad');}catch(e){setCam(`${e.name||'Error'}: ${e.message}`,'bad');}finally{$('refreshBtn').disabled=false;}}
function fill(sel,items,empty,allowNone=false){const prev=sel.value;sel.innerHTML='';if(allowNone){const o=document.createElement('option');o.value='';o.textContent='None';sel.appendChild(o);}for(const d of items){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label;o.dataset.label=d.label;sel.appendChild(o);}if(!items.length&&!allowNone){const o=document.createElement('option');o.value='';o.textContent=empty;sel.appendChild(o);}if([...sel.options].some(o=>o.value===prev))sel.value=prev;}
async function start(){try{if(!$('depthDevice').value)await refresh();if(!$('depthDevice').value)throw new Error('No D435 Depth input selected.');$('startBtn').disabled=true;const info=await source.start($('depthDevice').value,$('rgbDevice').value);running=true;busy=false;dropped=0;lastSent=0;originMatrix=null;path=[];keyframePath=[];trajectoryRows=[];worker.postMessage({type:'reset'});$('startBtn').textContent='Stop SLAM';setBadge('TRACKING','live');setCam(`${info.label} · ${info.width}×${info.height} · RGB ${info.rgb?'ON':'OFF'}`,'ok');schedule();}catch(e){setCam(`Start failed: ${e.message}`,'bad');setBadge('ERROR','bad');await source.stop();}finally{$('startBtn').disabled=false;}}
async function stop(){running=false;if(frameCb&&source.depthVideo?.cancelVideoFrameCallback){try{source.depthVideo.cancelVideoFrameCallback(frameCb);}catch{}}frameCb=null;await source.stop();$('startBtn').textContent='Start SLAM';setBadge('IDLE','idle');setCam('Stopped.');}
function schedule(){const loop=(now,meta)=>{if(!running)return;try{const depth=source.grabDepth(num('depthScale',.001),num('maxRange',4),meta);drawDepth($('depthCanvas'),depth,320,240,num('maxRange',4));$('cameraFps').textContent=`${source.cameraFps.toFixed(1)} Hz`;const target=Math.max(5,Math.min(30,num('targetHz',15))),period=1000/target;if(now-lastRgbDescAt>500){lastRgbDesc=source.rgbDescriptor();lastRgbDescAt=now;}if(now-lastSent>=period){if(!busy){busy=true;lastSent=now;const K=scaledK();const rgb=lastRgbDesc?lastRgbDesc.slice():null;worker.postMessage({type:'frame',depth:depth.buffer,w:320,h:240,K,maxCorr:num('maxCorr',.08),rgb:rgb?.buffer||null,timestamp:performance.now()},rgb?[depth.buffer,rgb.buffer]:[depth.buffer]);}else dropped++;}}catch(e){setCam(`Frame error: ${e.message}`,'bad');setBadge('ERROR','bad');}
    if(source.depthVideo?.requestVideoFrameCallback)frameCb=source.depthVideo.requestVideoFrameCallback(loop);else frameCb=setTimeout(()=>loop(performance.now(),null),33);
  };if(source.depthVideo?.requestVideoFrameCallback)frameCb=source.depthVideo.requestVideoFrameCallback(loop);else frameCb=setTimeout(()=>loop(performance.now(),null),0);}
function scaledK(){const sx=320/640,sy=240/480;return{fx:num('fx',381.902)*sx,fy:num('fy',381.902)*sy,cx:num('ppx',318.229)*sx,cy:num('ppy',239.945)*sy};}
function renderResult(m){currentRawPose=m.pose;currentMatrix=m.matrix;const p=relativePose(m.pose,m.matrix);$('trackingState').textContent=m.state;$('slamHz').textContent=`${m.slamHz.toFixed(1)} Hz`;$('computeMs').textContent=`${m.computeMs.toFixed(1)} ms`;$('dropped').textContent=String(dropped);$('inliers').textContent=String(m.inliers);$('rmse').textContent=Number.isFinite(m.rmse)?`${(m.rmse*1000).toFixed(1)} mm`:'—';$('keyframes').textContent=String(m.keyframes);$('loops').textContent=String(m.loops);$('relocalized').textContent=String(m.relocalized);$('posX').textContent=fmtM(p.x);$('posY').textContent=fmtM(p.y);$('posZ').textContent=fmtM(p.z);$('roll').textContent=fmtD(p.roll);$('pitch').textContent=fmtD(p.pitch);$('yaw').textContent=fmtD(p.yaw);setBadge(m.state,m.state==='TRACKING'?'live':m.state==='RELOCALIZED'?'live':m.state==='LOST'?'warn':'idle');path=m.path||path;keyframePath=m.keyframePath||keyframePath;trajView.render(path,keyframePath);trajectoryRows.push([performance.now(),p.x,p.y,p.z,p.roll,p.pitch,p.yaw,m.state,m.rmse,m.inliers]);}
function relativePose(p,matrix){if(!originMatrix||!matrix)return p;const R=mul4(invRigid(originMatrix),matrix),e=euler4(R);return{x:R[3],y:R[7],z:R[11],roll:e[0],pitch:e[1],yaw:e[2]};}
function invRigid(T){return[T[0],T[4],T[8],-(T[0]*T[3]+T[4]*T[7]+T[8]*T[11]),T[1],T[5],T[9],-(T[1]*T[3]+T[5]*T[7]+T[9]*T[11]),T[2],T[6],T[10],-(T[2]*T[3]+T[6]*T[7]+T[10]*T[11]),0,0,0,1];}
function mul4(a,b){const o=new Array(16).fill(0);for(let r=0;r<4;r++)for(let c=0;c<4;c++)for(let k=0;k<4;k++)o[r*4+c]+=a[r*4+k]*b[k*4+c];return o;}
function euler4(T){const pitch=Math.asin(Math.max(-1,Math.min(1,-T[8]))),roll=Math.atan2(T[9],T[10]),yaw=Math.atan2(T[4],T[0]),d=180/Math.PI;return[roll*d,pitch*d,yaw*d];}
function fmtM(v){return `${v>=0?'+':''}${v.toFixed(3)} m`;}function fmtD(v){return `${v>=0?'+':''}${v.toFixed(2)}°`;}
function num(id,f){const v=Number($(id).value);return Number.isFinite(v)?v:f;}function setCam(s,k=''){const e=$('cameraState');e.textContent=s;e.style.color=k==='ok'?'#3fb950':k==='bad'?'#f85149':'';}function setBadge(s,k){const e=$('statusBadge');e.textContent=s;e.className=`badge ${k||'idle'}`;}
function exportCsv(){let s='time_ms,x_m,y_m,z_m,roll_deg,pitch_deg,yaw_deg,state,rmse_m,inliers\n';for(const r of trajectoryRows)s+=r.join(',')+'\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download='d435-browser-slam-trajectory.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
refresh();
