let prev=null,w=320,h=240,K=null,pose=I(),frame=0,keyframes=[],loops=0,relocalized=0,lostCount=0,lastTime=0,slamHz=0,path=[],keyframePath=[];
onmessage=e=>{const m=e.data;if(m.type==='reset'){reset();postMessage({type:'reset'});return;}if(m.type==='benchmark'){benchmark();return;}if(m.type==='frame')processFrame(m);};
function reset(){prev=null;pose=I();frame=0;keyframes=[];loops=0;relocalized=0;lostCount=0;lastTime=0;slamHz=0;path=[];keyframePath=[];}
function processFrame(m){const t0=performance.now(),depth=new Float32Array(m.depth),rgb=m.rgb?new Uint8Array(m.rgb):null;w=m.w;h=m.h;K=m.K;frame++;let state='INITIALIZED',inliers=0,rmse=0;
  if(prev){const rel=track(depth,prev,poseGuess(),m.maxCorr||.08);inliers=rel.inliers;rmse=rel.rmse;if(rel.ok){pose=mul(pose,rel.T);state='TRACKING';lostCount=0;}else{lostCount++;const r=tryRelocalize(depth,rgb,m.maxCorr||.08);if(r){pose=r.pose;inliers=r.inliers;rmse=r.rmse;relocalized++;lostCount=0;state='RELOCALIZED';}else state='LOST';}}
  if(state!=='LOST'){const need=isKeyframe(pose)||(frame<3);if(need)addKeyframe(depth,rgb,pose,m.maxCorr||.08);}
  prev=depth;const e=euler(pose);path.push({x:pose[3],y:pose[7],z:pose[11]});if(path.length>3000)path.shift();const now=performance.now();if(lastTime){const hz=1000/(now-lastTime);slamHz=slamHz?slamHz*.9+hz*.1:hz;}lastTime=now;postMessage({type:'result',state,inliers,rmse,computeMs:performance.now()-t0,slamHz,keyframes:keyframes.length,loops,relocalized,pose:{x:pose[3],y:pose[7],z:pose[11],roll:e[0],pitch:e[1],yaw:e[2]},matrix:Array.from(pose),path:path.slice(-1500),keyframePath:keyframePath.slice(-500)});
}
function poseGuess(){return I();}
function isKeyframe(T){if(!keyframes.length)return true;const a=keyframes[keyframes.length-1].pose,d=rel(a,T);return trans(d)>.12||rot(d)>8*Math.PI/180||frame-a.frame>20;}
function addKeyframe(depth,rgb,T,maxCorr){const desc=depthDesc(depth);let best=null,bestScore=1e9;for(let i=0;i<keyframes.length-4;i++){const q=keyframes[i],ds=descDist(desc,q.dd),rs=(rgb&&q.rgb)?rgbDist(rgb,q.rgb):.5,score=ds*.7+rs*.3;if(score<bestScore){bestScore=score;best=q;}}
  if(best&&bestScore<.16&&frame-best.frame>45){const verify=track(depth,best.depth,I(),Math.max(.10,maxCorr*1.4),[12,8,5],[4,4,5]);if(verify.ok&&verify.inliers>120&&verify.rmse<.045){const corrected=mul(best.pose,verify.T),err=mul(inv(T),corrected);pose=corrected;T=pose;applyLightCorrection(err,best.frame);loops++;}}
  const kf={frame,pose:T.slice(),depth:depth.slice(),dd:desc,rgb:rgb?rgb.slice():null};keyframes.push(kf);if(keyframes.length>80)keyframes.shift();keyframePath.push({x:T[3],y:T[7],z:T[11]});}
function tryRelocalize(depth,rgb,maxCorr){const desc=depthDesc(depth);let cand=[];for(const q of keyframes){const ds=descDist(desc,q.dd),rs=(rgb&&q.rgb)?rgbDist(rgb,q.rgb):.5,score=ds*.75+rs*.25;if(score<.24)cand.push([score,q]);}cand.sort((a,b)=>a[0]-b[0]);for(const [,q] of cand.slice(0,4)){const r=track(depth,q.depth,I(),Math.max(.12,maxCorr*1.6),[14,9,6],[5,5,6]);if(r.ok&&r.inliers>100&&r.rmse<.055)return{pose:mul(q.pose,r.T),inliers:r.inliers,rmse:r.rmse};}return null;}
function applyLightCorrection(err,startFrame){const N=path.length;if(N<2)return;const tx=err[3],ty=err[7],tz=err[11];for(let i=0;i<N;i++){const a=(i+1)/N;path[i].x+=tx*a;path[i].y+=ty*a;path[i].z+=tz*a;}}
function depthDesc(d){const gx=16,gy=12,out=new Uint16Array(gx*gy);for(let by=0;by<gy;by++)for(let bx=0;bx<gx;bx++){let s=0,n=0;const x0=Math.floor(bx*w/gx),x1=Math.floor((bx+1)*w/gx),y0=Math.floor(by*h/gy),y1=Math.floor((by+1)*h/gy);for(let y=y0;y<y1;y+=3)for(let x=x0;x<x1;x+=3){const z=d[y*w+x];if(z>.15&&z<6){s+=z;n++;}}out[by*gx+bx]=n?Math.min(65535,Math.round((s/n)*10000)):0;}return out;}
function descDist(a,b){let s=0,n=0;for(let i=0;i<a.length;i++){if(a[i]&&b[i]){s+=Math.min(1,Math.abs(a[i]-b[i])/12000);n++;}}return n?s/n:1;}
function rgbDist(a,b){let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){const x=a[i]-128,y=b[i]-128;dot+=x*y;aa+=x*x;bb+=y*y;}return 1-(dot/(Math.sqrt(aa*bb)+1e-6)+1)*.5;}
function track(curr,ref,initial,maxCorr,steps=[12,7,4],iters=[4,5,6]){let T=initial.slice(),fin=0,rm=Infinity;for(let si=0;si<steps.length;si++){const step=steps[si];for(let it=0;it<iters[si];it++){const H=new Float64Array(36),g=new Float64Array(6);let count=0,sum=0;for(let v=2;v<h-2;v+=step)for(let u=2;u<w-2;u+=step){const z=curr[v*w+u];if(!(z>.12))continue;const p=deproj(u,v,z),tp=tpnt(T,p);if(tp[2]<=.1)continue;const pu=Math.round(K.fx*tp[0]/tp[2]+K.cx),pv=Math.round(K.fy*tp[1]/tp[2]+K.cy);if(pu<2||pv<2||pu>=w-2||pv>=h-2)continue;const qz=ref[pv*w+pu];if(!(qz>.12)||Math.abs(qz-tp[2])>maxCorr)continue;const n=normal(ref,pu,pv);if(!n)continue;const q=deproj(pu,pv,qz),rx=tp[0]-q[0],ry=tp[1]-q[1],rz=tp[2]-q[2],r=n[0]*rx+n[1]*ry+n[2]*rz;if(Math.abs(r)>maxCorr)continue;const wt=Math.abs(r)<.02?1:.02/Math.abs(r),J=[tp[1]*n[2]-tp[2]*n[1],tp[2]*n[0]-tp[0]*n[2],tp[0]*n[1]-tp[1]*n[0],n[0],n[1],n[2]];for(let i=0;i<6;i++){g[i]+=wt*J[i]*r;for(let j=0;j<6;j++)H[i*6+j]+=wt*J[i]*J[j];}count++;sum+=r*r;}fin=count;rm=count?Math.sqrt(sum/count):Infinity;if(count<45)return{ok:false,T,inliers:count,rmse:rm};for(let i=0;i<6;i++)H[i*6+i]+=1e-6;const rhs=new Float64Array(6);for(let i=0;i<6;i++)rhs[i]=-g[i];const dx=solve6(H,rhs);if(!dx)return{ok:false,T,inliers:count,rmse:rm};const mag=Math.hypot(...dx);if(!Number.isFinite(mag)||mag>.45)return{ok:false,T,inliers:count,rmse:rm};T=mul(exp6(dx),T);if(mag<1e-5)break;}}return{ok:fin>=65&&rm<Math.max(.045,maxCorr*.75),T,inliers:fin,rmse:rm};}
function normal(d,u,v){const zl=d[v*w+u-1],zr=d[v*w+u+1],zu=d[(v-1)*w+u],zd=d[(v+1)*w+u];if(!(zl&&zr&&zu&&zd))return null;const l=deproj(u-1,v,zl),r=deproj(u+1,v,zr),a=deproj(u,v-1,zu),b=deproj(u,v+1,zd),ax=r[0]-l[0],ay=r[1]-l[1],az=r[2]-l[2],bx=b[0]-a[0],by=b[1]-a[1],bz=b[2]-a[2];let nx=ay*bz-az*by,ny=az*bx-ax*bz,nz=ax*by-ay*bx,m=Math.hypot(nx,ny,nz);if(m<1e-7)return null;nx/=m;ny/=m;nz/=m;if(nz>0){nx=-nx;ny=-ny;nz=-nz;}return[nx,ny,nz];}
function deproj(u,v,z){return[(u-K.cx)*z/K.fx,(v-K.cy)*z/K.fy,z];}
function I(){return new Float64Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function mul(a,b){const o=new Float64Array(16);for(let r=0;r<4;r++)for(let c=0;c<4;c++){let s=0;for(let k=0;k<4;k++)s+=a[r*4+k]*b[k*4+c];o[r*4+c]=s;}return o;}
function tpnt(T,p){return[T[0]*p[0]+T[1]*p[1]+T[2]*p[2]+T[3],T[4]*p[0]+T[5]*p[1]+T[6]*p[2]+T[7],T[8]*p[0]+T[9]*p[1]+T[10]*p[2]+T[11]];}
function inv(T){return new Float64Array([T[0],T[4],T[8],-(T[0]*T[3]+T[4]*T[7]+T[8]*T[11]),T[1],T[5],T[9],-(T[1]*T[3]+T[5]*T[7]+T[9]*T[11]),T[2],T[6],T[10],-(T[2]*T[3]+T[6]*T[7]+T[10]*T[11]),0,0,0,1]);}
function rel(a,b){return mul(inv(a),b);}
function trans(T){return Math.hypot(T[3],T[7],T[11]);}
function rot(T){return Math.acos(Math.max(-1,Math.min(1,(T[0]+T[5]+T[10]-1)/2)));}
function exp6(x){const wx=x[0],wy=x[1],wz=x[2],th=Math.hypot(wx,wy,wz),T=I();let R;if(th<1e-9)R=[1,-wz,wy,wz,1,-wx,-wy,wx,1];else{const x1=wx/th,y1=wy/th,z1=wz/th,c=Math.cos(th),s=Math.sin(th),C=1-c;R=[c+x1*x1*C,x1*y1*C-z1*s,x1*z1*C+y1*s,y1*x1*C+z1*s,c+y1*y1*C,y1*z1*C-x1*s,z1*x1*C-y1*s,z1*y1*C+x1*s,c+z1*z1*C];}T[0]=R[0];T[1]=R[1];T[2]=R[2];T[4]=R[3];T[5]=R[4];T[6]=R[5];T[8]=R[6];T[9]=R[7];T[10]=R[8];T[3]=x[3];T[7]=x[4];T[11]=x[5];return T;}
function solve6(A,b){const M=new Float64Array(42);for(let r=0;r<6;r++){for(let c=0;c<6;c++)M[r*7+c]=A[r*6+c];M[r*7+6]=b[r];}for(let c=0;c<6;c++){let p=c;for(let r=c+1;r<6;r++)if(Math.abs(M[r*7+c])>Math.abs(M[p*7+c]))p=r;if(Math.abs(M[p*7+c])<1e-10)return null;if(p!==c)for(let j=c;j<7;j++){const t=M[c*7+j];M[c*7+j]=M[p*7+j];M[p*7+j]=t;}const d=M[c*7+c];for(let j=c;j<7;j++)M[c*7+j]/=d;for(let r=0;r<6;r++)if(r!==c){const f=M[r*7+c];for(let j=c;j<7;j++)M[r*7+j]-=f*M[c*7+j];}}const x=new Float64Array(6);for(let i=0;i<6;i++)x[i]=M[i*7+6];return x;}
function euler(T){const pitch=Math.asin(Math.max(-1,Math.min(1,-T[8]))),roll=Math.atan2(T[9],T[10]),yaw=Math.atan2(T[4],T[0]),d=180/Math.PI;return[roll*d,pitch*d,yaw*d];}
function benchmark(){const a=new Float32Array(320*240);for(let y=0;y<240;y++)for(let x=0;x<320;x++)a[y*320+x]=1.2+.001*x+.0007*y+.05*Math.sin(x*.04)*Math.cos(y*.03);w=320;h=240;K={fx:190.951,fy:190.951,cx:159.1145,cy:119.9725};const times=[];for(let i=0;i<18;i++){const t=performance.now();track(a,a,I(),.08);times.push(performance.now()-t);}times.sort((a,b)=>a-b);const median=times[Math.floor(times.length/2)],p95=times[Math.floor(times.length*.95)];postMessage({type:'benchmark',median,p95,recommendedHz:median<20?15:median<35?10:6});}
